# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: ImageRepository
  value: 'tmds/web'
- name: BuildContextWeb
  value: 'web'
- name: DockerfileWeb
  value: 'web/Dockerfile'
- name: ContainerRegistry
  value: 'DefaultDockerRegistryService'

steps:
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    containerRegistry: '$(ContainerRegistry)'
    buildContext: '$(BuildContextWeb)'
    Dockerfile: '$(Build.SourcesDirectory)/$(DockerfileWeb)'
    repository: '$(ImageRepository)'
    tags: latest
- task: Docker@2
  displayName: Login
  inputs:
    command: login
    containerRegistry: '$(ContainerRegistry)'
- task: Docker@2
  displayName: Push Image
  inputs:
    command: push
    containerRegistry: '$(ContainerRegistry)'
    repository: '$(ImageRepository)'
    tags: latest
