trigger:
- main

variables:
- name: BuildContext        # Source directory for the image build
  value: 'web'
- name: Dockerfile          # Source location of Dockerfile
  value: 'web/Dockerfile'
- name: HelmChart           # Source location of Helm chart
  value: 'helm/dotnet-chart'
- name: RegistryService     # Image registry service connection name
  value: 'DefaultDockerRegistryService'
- name: RegistryServer      # Hostname of the registry
  value: 'quay.io'
- name: ImageName           # Name of the image
  value: 'tdeseyn/web'
- name: ImageTag            # Image tag
  value: $(Build.SourceVersion)
- name: Environment         # Azure DevOps target environment
  value: 'StagingEnvironment'
- name: EnvironmentResource # Azure DevOps target resource
  value: 'tdeseyn-stage'
- name: Namespace           # Target Kubernetes namespace
  value: 'tdeseyn-stage'
- name: ReleaseName         # Name of the Helm release
  value: 'web'
- name: ImagePullSecret     # Kubernetes secret for pulling from image registry
  value: 'pullsecret'

jobs:
- job: Build
  steps:
  - task: Docker@2
    displayName: Build and push Image
    inputs:
      command: buildAndPush
      containerRegistry: $(RegistryService)
      buildContext: '$(BuildContext)'
      Dockerfile: '$(Build.SourcesDirectory)/$(Dockerfile)'
      repository: '$(ImageName)'
      tags: $(ImageTag)
- deployment: Deploy
  dependsOn: Build
  environment: $(Environment).$(EnvironmentResource)
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: KubernetesManifest@0
          displayName: Bake Manifests
          inputs:
            action: bake
            namespace: $(Namespace)
            helmChart: $(HelmChart)
            releaseName: $(ReleaseName)
            overrides: |
              build.enabled:false
              image.name:$(RegistryServer)/$(ImageName)
            containers: |
              $(RegistryServer)/$(ImageName):$(ImageTag)
        - task: KubernetesManifest@0
          displayName: Deploy Manifests
          inputs:
            action: deploy
            manifests: $(bake.manifestsBundle)
            namespace: $(Namespace)
            imagePullSecrets: $(ImagePullSecret)
            releaseName: $(ReleaseName)