# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: ImageRepository
  value: tmds/web
- name: BuildContextWeb
  value: web
- name: DockerfileWeb
  value: web/Dockerfile

steps:
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    buildContext: $(BuildContextWeb)
    Dockerfile: $(Build.SourcesDirectory)/$(DockerfileWeb)
    repository: $(ImageRepository)
    tags: latest
