trigger:
- main

variables:
- name: BuildContext        # Source directory for the image build
  value: 'web'
- name: Dockerfile          # Source location of Dockerfile
  value: 'web/Dockerfile'
- name: HelmChart           # Source location of Helm chart
  value: 'helm/dotnet-chart'
- name: RegistryService     # Image registry service connection name
  value: 'DefaultDockerRegistryService'
- name: Image               # Name of the image
  value: 'tdeseyn/web'
- name: ImageTag            # Image tag
  value: $(Build.BuildId)
- name: RegistryServer      # Hostname of the registry
  value: 'quay.io'
- name: Environment         # Azure DevOps target environment
  value: 'StagingEnvironment'
- name: EnvironmentResource # Azure DevOps target resource
  value: 'tdeseyn-stage'
- name: Namespace           # Target Kubernetes namespace
  value: 'tdeseyn-stage'
- name: ReleaseName         # Name of the Helm release
  value: 'web'
- name: ImagePullSecret     # Kubernetes secret for pulling from image registry
  value: 'pullsecret'

jobs:
- job: Build
  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      containerRegistry: $(RegistryService)
      buildContext: '$(BuildContext)'
      Dockerfile: '$(Build.SourcesDirectory)/$(Dockerfile)'
      repository: '$(Image)'
      tags: $(ImageTag)
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: $(RegistryService)
  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      containerRegistry: $(RegistryService)
      repository: '$(Image)'
      tags: $(ImageTag)
- deployment: Deploy
  environment: $(Environment).$(EnvironmentResource)
    # name: 
    # resourceName: '$(EnvironmentResource)'
    # resourceType: Kubernetes
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: KubernetesManifest@0
          name: bake
          displayName: Render Helm Chart
          inputs:
            action: 'bake'
            namespace: $(Namespace)
            helmChart: $(HelmChart)
            releaseName: $(ReleaseName)
            overrides: |
              build.enabled:false
              image.name:$(RegistryServer)/$(Image)
              image.tag:$(ImageTag)
        - task: KubernetesManifest@0
          displayName: Deploy Manifests
          inputs:
            manifests: $(bake.manifestsBundle)
            namespace: $(Namespace)
            imagePullSecrets: $(ImagePullSecret)
            releaseName: $(ReleaseName)