# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: ImageRepository
  value: 'tdeseyn/web'
- name: BuildContextWeb
  value: 'web'
- name: DockerfileWeb
  value: 'web/Dockerfile'
- name: ContainerRegistry
  value: 'DefaultDockerRegistryService'
- name: Namespace
  value: 'tdeseyn-stage'

jobs:
- job: Build
  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      containerRegistry: '$(ContainerRegistry)'
      buildContext: '$(BuildContextWeb)'
      Dockerfile: '$(Build.SourcesDirectory)/$(DockerfileWeb)'
      repository: '$(ImageRepository)'
      tags: latest
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: '$(ContainerRegistry)'
  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      containerRegistry: '$(ContainerRegistry)'
      repository: '$(ImageRepository)'
      tags: latest
- deployment:
  environment:
    name: StagingEnvironment
    resourceName: 'tdeseyn-stage'
    resourceType: Kubernetes
  strategy:
    runOnce:
      deploy:
        steps:
        - task: HelmDeploy@0
          displayName: Helm Upgrade
          inputs:
            command: upgrade
            chartType: FilePath
            chartPath: helm/dotnet-chart/Chart.yaml
            namespace: 'tdeseyn-stage'
            overrideValues: |
              build.enabled='false'
              image.name='quay.io/tdeseyn/web'
              image.tag='latest'
