apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet.name" . }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  template:
    metadata:
      labels:
        {{- include "dotnet.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: {{ include "dotnet.imageName" . }}

